query GetTicketDetailsQuery ($ticketId: String!) {
    clear {
        ticket(where: {id: $ticketId}) {
            id
            age
            firstName
            lastName
            guardian {
                email
            }
            event {
                name
                majorityAge
            }
        }
    }
}
