#import "../../components/IndexHeader.gql"
#import "../../components/StudentQuotes.gql"

query IndexStaticPathsQuery {
  cms {
    regions(limit: 1000) {
      items {
        webname
        aliases
      }
    }
  }
}

query IndexStaticPropsQuery ($webname: String! $endDate: ClearDateTime!) {
  cms {
    regions(where:{ OR: [{ webname: $webname }, { aliases_contains_all: [$webname] }] }, limit: 1) {
      items {
        name
        webname
      }
    }
  }

  clear {
    findFirstEvent(where: {contentfulWebname: {equals: $webname}, endDate: {gte: $endDate}}, orderBy: {startDate: desc}) {
      id
      canRegister
      canEarlyBirdRegister
      activeTicketPrice
      displayDate
      earlyBirdCutoff
      registrationCutoff
      minAge
      maxAge
      majorityAge
      eventGroup {
        name
      }
      venue {
        name
        address
        mapLink
      }
    }
  }
  ...IndexHeaderFragment
  ...StudentQuotesFragment
}

