#import "../components/Organize/OrganizerTestimonials.gql"
#import "../components/Organize/PullQuote.gql"
#import "../components/PastProjects.gql"

query OrganizePageQuery {
  ...OrganizerTestimonials
  ...PastProjects
  cms {
    quoteNothingLikeSchool: testimonial(id:"2gAsdYLfoK3v9sLuWnAwAt") { ...PullQuote }
    quoteCreative: testimonial(id:"1NjU0FSdK0hRV4g6l4X1EZ") { ...PullQuote }
  }
}
