fragment ClearEventInfo on ClearEvent {
  name
  contentfulWebname
  startDate
  displayDate
}

query UpcomingPageQuery ($clearDate: ClearDateTime!) {
  clear {
    open: events (where: { endDate: { gte: $clearDate }, registrationsOpen: { equals: true } }) {
      ...ClearEventInfo
    }
    closed: events (where: { endDate: { gte: $clearDate }, registrationsOpen: { equals: false } }) {
      ...ClearEventInfo
    }
  }
  cms {
    regions (limit: 500) {
      items {
        name
        webname
      }
    }
  }
}