fragment ClearEventInfo on ClearEvent {
  name
  contentfulWebname
  startDate
  displayDate
}

query UpcomingPageQuery ($clearDate: ClearDateTime!, $locale: String!) {
  clear {
    open: events (where: { endDate: { gte: $clearDate }, registrationsOpen: { equals: true } }) {
      ...ClearEventInfo
    }
    closed: events (where: { endDate: { gte: $clearDate }, registrationsOpen: { equals: false } }) {
      ...ClearEventInfo
    }
  }
  cms {
    regions (limit: 500, locale: $locale) {
      items {
        name
        webname
      }
    }
  }
}