fragment PastPhotos on CmsRegion {
  featuredPhotos: pastPhotos (where: { program: "codeday", featured: true }, take: 27, orderBy: RANDOM) {
    id
    urlMedium
    thanks
  }
  pastPhotos (where: { program: "codeday" }, take: 54, orderBy: RANDOM) {
    id
    urlMedium
    thanks
  }
}
