query RefreshRemainingQuery($eventId: String!) {
  clear {
    event(where: { id: $eventId }){
      remainingTickets
    }
  }
}

mutation RegisterMutation(
  $eventId: String!,
  $ticketsData: [ClearTicketCreateWithoutEventInput!]!,
  $guardianData:  ClearPersonCreateInput,
  $promoCode: String,
  $paymentProvider: ClearPaymentProvider,
) {
    clear {
        registerForEvent(
            eventWhere: {id: $eventId},
            guardianData: $guardianData,
            ticketsData: $ticketsData,
            promoCode: $promoCode,
            paymentProvider: $paymentProvider,
        )
    }
}

mutation FinalizePaymentMutation($paymentIntentId: String!, $paymentProvider: ClearPaymentProvider) {
  clear {
    finalizePayment(paymentIntentId: $paymentIntentId, paymentProvider: $paymentProvider)
  }
}

mutation WithdrawFailedPaymentMutation($paymentIntentId: String!, $paymentProvider: ClearPaymentProvider) {
  clear {
    withdrawFailedPayment(paymentIntentId: $paymentIntentId, paymentProvider: $paymentProvider)
  }
}


