query RefreshRemainingQuery($eventId: String!) {
  clear {
    event(where: { id: $eventId }){
      remainingTickets
    }
  }
}

mutation RegisterMutation($eventId: String!, $ticketsData: [ClearTicketCreateWithoutEventInput!]!, $guardianData:  ClearPersonCreateInput, $promoCode: String) {
    clear {
        registerForEvent(
            eventWhere: {id: $eventId},
            guardianData: $guardianData,
            ticketsData: $ticketsData,
            promoCode: $promoCode
        )
    }
}

mutation FinalizePaymentMutation($paymentIntentId: String!) {
  clear {
    finalizePayment(paymentIntentId: $paymentIntentId)
  }
}

mutation WithdrawFailedPaymentMutation($paymentIntentId: String!) {
  clear {
    withdrawFailedPayment(paymentIntentId: $paymentIntentId)
  }
}


