fragment GlobalSponsors on CmsQuery {
  globalSponsors (order: sys_firstPublishedAt_ASC) {
    items{
      link
      name
      type
      logo {
        url(transform:{height: 60})
        small: url(transform:{height: 20})
      }
      darkLogo {
        url(transform:{height: 60})
        small: url(transform:{height: 20})
      }
    }
  }
}

fragment LocalSponsorsFragment on ClearEvent {
  sponsors (orderBy:{createdAt: asc}) {
    id
    name
    description
    link
    logoImageUri
    darkLogoImageUri
  }
}
