fragment PublicPersonFragment on ClearPublicPerson {
  firstName
  lastName
  account {
    name
    pronoun
    picture
  }
  avatarUrl
}

fragment AccountPersonFragment on AccountUser {
  name
  picture
  pronoun
}

fragment TeamFragment on ClearEvent {
  team {
    staff {
      ...PublicPersonFragment
    }

    mentors {
      ...PublicPersonFragment
    }

    judges {
      ...PublicPersonFragment
    }
  }
}

fragment GlobalTeamFragment on Query {
  globalTeam: account {
    employees: roleUsers (roleId: "rol_llN0357VXrEoIxoj") {
      ...AccountPersonFragment
    }

    otherTeam: roleUsers (roleId: "rol_6t902YZpsOynmWDt") {
      ...AccountPersonFragment
    }
  }
}