query RetrieveSurveyResponses ($ticket: String!, $privateKey: String!) {
  clear {
    retrieveTicketInfo(where:{id: $ticket}, privateKey: $privateKey) {
      id
      privateKey
      firstName
      lastName
      surveyResponses
      age
      promoCode {
        metadata
      }
    }
  }
}